package main

var searhStrings = []string{
	"dool",
	"denial of god",
	"beast in black",
	"tuska",
	"alestorm",

	"avatarium",
	"alfahanne",
	"alien weaponry",
	"anomalie",
	"asaf avidan",
	"batushka",
	"beast in black",
	"brothers of metal",
	"celtefog",
	"crippled black phoenix",
	"denial of god",
	"dool",
	"dynazty",
	"edguy",
	"empereor",
	"enslaved",
	"first aid kit",
	"flogging molly",
	"florence",
	"george ezra",
	"gogol bordello",
	"groza",
	"heavy metal perse",
	"the hu",
	"immortal",
	"iron maiden",
	"katzenjammer",
	"kaz hawkins",
	"kvaen",
	"long distance calling",
	"lumineers",
	"manowar",
	"mayhem",
	"mgla",
	"molybaron",
	"mono inc",
	"moonsorrow",
	"moonspell",
	"mumford",
	"nightwish",
	"nostalghia",
	"of monsters and men",
	"patrick wolf",
	"powerwolf",
	"primordial",
	"queen",
	"rotting christ",
	"sacred outcry",
	"santiano",
	"saor",
	"schammasch",
	"shining",
	"sleep of monsters",
	"steve 'n' seagulls",
	"turisas",
	"uriah heep",
	"vreid",
	"vulture industries",
	"w.a.s.p.",
	"wildhearts",
}
